import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Script src="/javascript/lofi-music-manager.js"></Script>
        <Script src="/javascript/songs/avalanche.js"></Script>
        <Script src="/javascript/songs/chess.js"></Script>
        <Script src="/javascript/songs/fight-cub.js"></Script>
        <Script src="/javascript/songs/orbital-launch.js"></Script>
        <Script src="/javascript/songs/sketch-ball.js"></Script>
        <Script src="/javascript/songs/wheely.js"></Script>
        <Script src="/javascript/songs/boating-school.js"></Script>
        <Script src="/javascript/songs/cube-dance.js"></Script>
        <Script src="/javascript/songs/grove-tender.js"></Script>
        <Script src="/javascript/songs/rail-layer.js"></Script>
        <Script src="/javascript/songs/space-quest.js"></Script>
        {children}
      </body>
    </html>
  );
}
